<template>
  <div class="about">
    <h1>This is an about page</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam, nam officiis quaerat ab, perspiciatis inventore hic tempora exercitationem nostrum earum sapiente tenetur harum adipisci quisquam. Dicta, fugiat. Deleniti, nesciunt nam.
    Maiores reprehenderit exercitationem commodi repellendus nihil tempora quis quos quasi voluptas, ipsa maxime odit, cupiditate repellat sapiente sit corporis alias ex optio id totam velit quidem. Et optio harum obcaecati!
    Tempora velit neque quam quod minus molestias a cum ad, error eveniet, laboriosam omnis vero, esse optio. Corrupti quas quis dignissimos, molestias provident debitis, tempora id nobis itaque, voluptate veniam.
    Itaque cumque ipsum ducimus adipisci distinctio consequuntur temporibus similique, excepturi commodi porro est nobis in voluptate, quidem explicabo. Sit, nisi. Sequi recusandae nihil odit debitis, magnam provident unde reiciendis velit.
    Quae inventore fugit modi atque! Corporis, blanditiis consectetur quia veritatis unde porro placeat asperiores delectus eius obcaecati at ex, cum nam incidunt explicabo. Dolor id, magnam delectus eaque minus corrupti.
    Facere consequuntur, iste molestias quasi culpa quidem qui quod eligendi, asperiores accusantium assumenda. Blanditiis reiciendis et consectetur quae quibusdam, laborum, quidem tempora velit eaque necessitatibus eveniet impedit, quo ipsum? Nesciunt.
    Sunt culpa impedit itaque inventore natus porro aliquam, at cupiditate maiores aperiam minima molestias dicta reiciendis perferendis facilis, exercitationem obcaecati quaerat officia necessitatibus fugit labore. Perferendis delectus tempore harum doloremque.
    Soluta rem vitae veritatis sapiente enim consectetur? Similique deserunt nesciunt expedita nemo, error sint possimus quisquam velit saepe labore sequi non sapiente inventore ducimus dolor corrupti quos nobis ab. Sequi.
    Iure quibusdam labore nobis tempore odio doloribus assumenda blanditiis consequuntur molestias, omnis nihil sint nostrum modi magni itaque autem expedita dignissimos perferendis delectus! Tempora suscipit excepturi rerum non, ad ea?
    Inventore saepe iste officia id odio harum ratione sed optio labore expedita, aspernatur accusamus unde quo repellendus in voluptates nobis repellat quibusdam quae praesentium accusantium non soluta iure possimus! Atque.
    Asperiores velit voluptas molestias a laborum possimus repellat! Enim, deserunt blanditiis? Modi quo delectus consequatur asperiores rem, sit ipsa consectetur distinctio quos inventore officiis. Nihil ut soluta sequi non culpa!
    Ducimus at aliquam nemo non nesciunt molestiae tempora temporibus, mollitia ipsam accusantium dolorem consequatur nobis eaque voluptatum nisi molestias nulla corporis eveniet error blanditiis nam. Sapiente eum a molestiae reprehenderit.
    Fuga distinctio et tempore deserunt, totam omnis cum unde dicta. Cum omnis, assumenda saepe repellat magnam dolores doloremque fuga, incidunt quis tempore deserunt, fugit laboriosam voluptate perferendis quas quia aliquid.
    Animi iure atque ullam doloribus nobis sed et perferendis, officiis perspiciatis repudiandae, possimus corrupti. Aspernatur sunt nulla accusantium dolorem veritatis numquam excepturi qui, possimus molestiae a? Sequi culpa natus temporibus.
    Autem veniam minus explicabo sint debitis dicta dolorem hic, quos ex soluta architecto non libero. Inventore neque veniam eum iste, officiis, repudiandae aliquid ex, et tempora corrupti quibusdam officia cum!
    Repellat hic nemo rerum dignissimos quae corporis eius autem ipsa dolor earum fugiat nam non, sequi id doloremque facere. Totam natus quas consectetur quidem. Recusandae ipsum inventore aut eos dolor.
    Tempora dolorem iste dicta rerum ea tenetur mollitia repudiandae, corporis qui quo distinctio. Velit quasi ut perferendis ipsa fugiat distinctio neque impedit beatae error consequatur assumenda in qui, porro itaque!
    Debitis esse obcaecati perferendis aliquam numquam sunt eius blanditiis autem, ipsum distinctio magnam enim tenetur cumque, itaque quod aspernatur, inventore iure! Reiciendis vero nihil nemo quia. Eligendi expedita magni ipsam.
    Optio ratione enim facilis earum voluptas blanditiis consequuntur odit eligendi cupiditate obcaecati fugit repudiandae doloremque necessitatibus dolore explicabo pariatur at, quo molestias eveniet atque eos similique nostrum ad. Expedita, harum.
    Nostrum dignissimos odio itaque perferendis! Reiciendis delectus amet vitae, est reprehenderit, velit accusamus error minima expedita ipsa quaerat, facilis eum molestiae. Perferendis voluptatum quaerat explicabo nemo illum, sint assumenda magni.
    Earum quas sunt dignissimos nostrum delectus, architecto adipisci libero corporis asperiores, officiis ducimus? Rerum, quis magnam amet non error hic temporibus enim quod ab provident quasi eveniet eius quisquam atque.
    Id recusandae distinctio voluptates libero, repudiandae ullam possimus illo quos enim quod incidunt saepe maxime neque, beatae quaerat molestias dolorem nihil numquam sint in fugiat doloribus praesentium deleniti. Nostrum, quia.
    Tempore hic, quo qui nemo, deserunt consequuntur ut, nulla dolore quaerat velit voluptas suscipit aperiam itaque est. Expedita, nostrum numquam quas, id earum asperiores praesentium, autem culpa libero reiciendis dolorem.
    Quia facilis quidem harum quam reiciendis debitis non commodi magnam illum? Velit error corrupti ex totam non veniam id, magnam neque eligendi, corporis maxime iusto voluptate quia, odio quibusdam quo.
    Excepturi ducimus consectetur tempore fuga. Quae quasi incidunt a ad quos mollitia consequuntur tempore? Consequatur ipsa sit rerum et. Earum molestias quaerat iure veritatis est accusamus corrupti adipisci possimus facilis.
    Odio itaque corrupti eaque aspernatur et ut asperiores similique dolore sapiente? Quos reiciendis beatae nam nihil quae excepturi aut, enim ex fugit, quaerat laborum expedita officiis quo. Harum, aliquam officiis?
    Eius amet maxime quia reprehenderit incidunt temporibus provident fugit ut cumque, assumenda omnis officiis earum fuga at quae, ipsam dignissimos similique a totam? Eveniet unde, numquam et assumenda deserunt labore.
    Temporibus architecto ullam deleniti. Consequuntur cumque excepturi distinctio architecto dolorum facere quam corrupti molestias quod, nisi dolorem sed illum sequi quibusdam odio sunt, accusantium suscipit in recusandae deleniti rem! Quaerat?
    Distinctio commodi ad, dolor unde enim dolorum voluptatum eum architecto. Eaque ipsam autem quos eum, obcaecati expedita voluptates? Recusandae aliquam necessitatibus cupiditate rem voluptatibus eum excepturi doloribus aspernatur odio reiciendis!
    Cum accusantium adipisci omnis quasi atque reprehenderit, minima provident accusamus odio excepturi eos iure temporibus labore. Laborum corrupti fuga quibusdam. Nam et explicabo error aliquam numquam dolore quaerat illum sint.
    Cum labore, repellat deleniti voluptatibus voluptate repellendus omnis aliquid molestias ea, placeat asperiores nam hic nulla magnam officia quis quaerat atque quia perspiciatis exercitationem ut sed beatae reiciendis! Officiis, ex.
    Cum, odio ut dignissimos beatae incidunt fuga vero, est possimus, suscipit sequi tempore iste saepe quia repudiandae eligendi similique non sapiente. Debitis temporibus non explicabo aperiam, dolorem deserunt rem repellendus.
    Sunt eos rerum veniam, velit explicabo magni temporibus vero dolorum impedit quasi placeat fugiat, enim dignissimos voluptatibus ipsum unde non assumenda dolores provident corporis quae, perspiciatis numquam? Voluptatibus, quidem magni.
    Ut ea corrupti fugit ratione eligendi fuga dolorum a aliquid repellat, itaque vitae dolores, harum soluta voluptatum ex tempore nam. Deserunt similique sunt cumque quo vel neque, nihil amet vitae!
    Commodi velit natus aliquid. Voluptatibus modi possimus, magnam perferendis distinctio rem sapiente tempora facere et? Eaque voluptatem explicabo ipsa optio, praesentium quia quod sed recusandae quam? Culpa quaerat animi nobis.
    Delectus nihil voluptate deleniti ducimus hic fugit ratione ad consequatur, officiis beatae? Est consequuntur temporibus culpa modi quibusdam voluptas sint, minus laborum voluptatum corrupti libero accusamus quos debitis possimus reiciendis!
    Voluptatum ad, eligendi adipisci dolore illo iure nostrum obcaecati dolorem, cupiditate error recusandae in rerum distinctio natus eius doloremque nobis quisquam quos at rem quis officiis eaque! Maiores, quae reprehenderit.
    Voluptatum voluptates animi aperiam rerum facere eum reprehenderit beatae quo necessitatibus sequi dolorem recusandae minima, est perferendis ut dolor rem nam reiciendis vero. Totam, hic sit possimus aut nihil quia?
    Saepe molestias animi rem blanditiis omnis sed quis laboriosam laborum error fuga. A soluta exercitationem nihil, veniam consectetur aperiam cum voluptatem possimus nulla ducimus sit dolorum et repudiandae voluptatum adipisci!
    Quidem repellendus provident odit doloremque blanditiis! Magnam possimus minus ipsam iste repellendus aspernatur dicta inventore at dolorem voluptatibus. Minima, numquam aliquid provident a mollitia pariatur maiores suscipit voluptatibus dolor porro.
    Odit quidem qui temporibus expedita sequi cum laboriosam repudiandae nulla rerum obcaecati, excepturi ex sit? Velit eaque veniam voluptate similique iste, obcaecati, magnam numquam molestias corporis ea odio sunt debitis.
    Recusandae, aliquam! Explicabo hic qui quam voluptatum minus voluptas eius officia cumque, corrupti exercitationem, alias fugit. Quas, inventore esse iusto eum doloribus debitis assumenda perspiciatis ducimus, totam dolorem possimus sapiente.
    Similique harum nulla vel sit provident quo non dolores corrupti velit ducimus praesentium laboriosam, asperiores eaque error eligendi! Nesciunt, tenetur suscipit quis quia odit earum quibusdam fuga vel est aliquam.
    Repudiandae in voluptate consectetur. Modi, voluptatum molestias atque saepe, cum error adipisci culpa nam qui illum unde blanditiis maiores iure ab. Expedita, incidunt officia repudiandae voluptas quia reprehenderit odit? Eum!
    Fugit corrupti sit quos optio dignissimos obcaecati, adipisci deserunt doloribus sequi non suscipit consectetur, nemo earum temporibus id laudantium dicta. Iure deleniti eaque voluptatem laborum totam nemo dolore eos vero?
    Deleniti quibusdam atque nam nihil magni. Consequatur expedita minus hic exercitationem iste aspernatur possimus aliquam voluptatem similique fuga. Expedita asperiores ab enim! Ex obcaecati labore in eligendi optio. Vel, voluptatum?
    Impedit iure veritatis, suscipit ea vel provident qui beatae maxime, dolorem culpa nostrum adipisci temporibus perspiciatis consequuntur, pariatur est porro voluptate laboriosam ad harum. Obcaecati cumque rerum in quam esse.
    Quibusdam accusantium temporibus sapiente illum impedit sunt dolor, reprehenderit aperiam! Quaerat eaque quibusdam, tenetur accusantium, sequi ab labore nemo nesciunt debitis iste, culpa quo! Expedita voluptatibus cumque magnam illo nesciunt!
    Quos saepe voluptatem doloribus aut vitae accusamus quidem minima praesentium quod, alias provident temporibus totam iure dolor animi recusandae unde placeat quas! Id distinctio itaque nostrum quam perferendis tenetur reprehenderit!
    Quia consequuntur fuga nemo, eius deleniti itaque vero architecto ab autem provident repudiandae voluptatem praesentium totam quos quod placeat necessitatibus recusandae ipsa! Non sint fugiat aliquid error numquam, voluptatem illum!
    Dicta doloremque, facere nam suscipit molestias accusamus sint dolorem? Assumenda placeat deserunt, iste qui fugiat iure quae ab. Quaerat quos eligendi enim consequuntur numquam ullam labore fuga molestias est fugit!
    Tempore nam perspiciatis impedit perferendis dolores nostrum rem quos. Accusantium aperiam quis laborum vitae magni recusandae sint quaerat? Odit eos natus accusantium? Molestias a tenetur voluptas mollitia ab! Modi, ipsum!
    Veritatis, quia necessitatibus voluptatem accusantium itaque nisi? Facilis asperiores, illo distinctio, beatae voluptas repellat reprehenderit vel necessitatibus vitae deserunt quaerat voluptates deleniti quae, laborum delectus! Odit dicta magni unde sequi.
    Dolorum iusto et odit ipsam! Obcaecati, blanditiis maxime. Quas temporibus doloremque eveniet eos iure est eaque dolorem atque nam maxime similique perspiciatis possimus quos distinctio magnam, cumque deserunt minima consequatur?
    Omnis quod nostrum ex! Ad praesentium perspiciatis a accusantium magnam aspernatur dolorem repellendus eveniet? Repellendus labore quia a vitae esse, rem nisi modi. Culpa molestiae consectetur ullam, tempore eum adipisci!
    Soluta, laboriosam facilis mollitia temporibus voluptatem deleniti? Unde voluptatem facilis, laborum dolores ullam, reprehenderit iusto, deserunt consequuntur provident nemo qui ratione adipisci? Maxime exercitationem numquam veniam maiores quae dicta eligendi!
    Accusamus quaerat eaque quia? Nulla explicabo tempore dolorum cumque, quos ullam ipsum, atque facere mollitia reiciendis, blanditiis voluptas animi quod autem id corrupti expedita rem architecto pariatur ipsam adipisci perferendis.
    Placeat omnis maxime, ratione veritatis illum doloribus autem dolorem, eaque minima consequatur voluptatum voluptatem? Molestiae veritatis voluptatum mollitia aliquid, laborum aut quibusdam laudantium exercitationem odio in dignissimos dolorem. Consequuntur, sequi?
    Ab veniam rerum minima velit sunt facilis quasi ad blanditiis beatae aut. Quia commodi voluptatibus atque placeat vel! Nostrum voluptatibus rerum doloribus fugiat provident cumque alias vero recusandae atque optio?
    Nesciunt molestiae, illum excepturi iste assumenda fugit in voluptatem adipisci eius quasi a, repudiandae, porro dolorum necessitatibus laboriosam modi. Assumenda perferendis asperiores qui illo autem consequuntur culpa ipsam velit facere!
    Corrupti error laborum ipsum id saepe magni repellendus nam incidunt delectus quisquam aspernatur, libero facere commodi sint alias, dolore sequi atque repudiandae laboriosam culpa dolorem obcaecati nulla explicabo? Ipsa, porro?
    Consequatur, illum? Vero ad eligendi alias nihil, maiores fuga obcaecati minima ratione aliquid? Id sint tempore tempora unde officia pariatur nemo excepturi, quo soluta laudantium in, ut modi dicta necessitatibus?
    Libero quaerat incidunt numquam dolores omnis nobis adipisci tempore, accusantium reiciendis aperiam. Repellat quam corrupti facere iusto. Odio, quaerat. Magnam aliquid praesentium minus non vitae cumque voluptatem consequuntur nisi omnis.
    Maxime reiciendis quidem commodi veritatis illum fugit dolor, quis corporis a! Dignissimos perspiciatis cupiditate repudiandae saepe explicabo, assumenda incidunt, voluptatum labore adipisci repellendus consequuntur voluptates vitae alias vel, natus numquam!
    Numquam dolorum, saepe rem error illum repellendus molestiae nulla nesciunt enim magni asperiores. Laboriosam ipsa dolore, minus voluptates delectus distinctio dignissimos ut error pariatur maxime animi cumque impedit nostrum aperiam.
    Rerum vero eligendi debitis illum aliquid est dolor quos, vitae, hic veniam dolores omnis. Provident repudiandae, suscipit expedita ut quas placeat itaque repellendus quod amet molestias ea, est quisquam? Nulla?
    Ea voluptas nihil amet enim incidunt delectus fugit voluptatibus, labore nisi excepturi! Impedit in maiores illo, earum perferendis nobis nemo excepturi sapiente quibusdam quidem. Perferendis, esse ipsa. Tempora, sit voluptatum.
    Quo optio sed asperiores ad quae deserunt suscipit veritatis quisquam, harum culpa nemo tempore deleniti ex repudiandae voluptatem, dolor eligendi, laborum cum! Fugit, facilis earum aliquid incidunt voluptatem optio nemo.
    Incidunt veniam eius rerum voluptatum, blanditiis explicabo at est voluptates distinctio adipisci dignissimos, soluta suscipit pariatur debitis deserunt, placeat architecto libero! Et non obcaecati voluptates similique alias maxime! Nihil, tempora?
    Repudiandae dolore voluptatum veniam, magnam nostrum quis commodi illo nulla quibusdam dolorum quisquam et optio eveniet temporibus ullam cumque quia non quos distinctio. Saepe quibusdam tempora molestias ipsa corporis? Aut!
    Distinctio hic sequi saepe eum ex fugiat omnis aperiam excepturi quia impedit dicta possimus quam animi ratione repellat repellendus, beatae consectetur facilis dolorum fugit dolorem odio. Excepturi mollitia dignissimos ullam.
    Culpa assumenda labore fugit perferendis earum nobis dolorum corrupti nisi tenetur? Quia ad eaque fugit quaerat error assumenda magnam, tenetur voluptate incidunt. Aliquid ipsa repellendus consectetur maxime eius rerum deleniti.
    Quis officia dignissimos placeat dolorem ab pariatur autem mollitia cumque ex quia culpa ipsa voluptates neque sed, aspernatur est error eum quod eius perferendis, rem ea tenetur hic? A, hic!
    Nemo eius itaque eligendi dolor esse porro mollitia alias cum! Officiis ullam libero repudiandae ipsam pariatur maxime consectetur temporibus id saepe accusantium, cupiditate nesciunt mollitia laborum. Maiores facilis aut enim?
    Fuga labore architecto consectetur, eos quo quos aut explicabo, culpa sint mollitia, expedita assumenda magnam cumque obcaecati accusamus? Ea deleniti corporis qui sunt! Adipisci velit pariatur dolorum eos placeat voluptate.
    Molestiae aut quod non obcaecati at minima, rerum doloremque corporis modi harum? Ea, nostrum? Nobis laudantium quidem dolor atque provident, laboriosam, dicta ipsum consectetur amet culpa, earum similique sint illo?
    Praesentium aliquid atque quia, iure optio ab minus voluptate officiis odio animi sunt cumque fugiat neque aperiam ipsam eius. Fugit eaque similique nisi autem! Temporibus magnam maxime ipsam blanditiis harum?
    Ea, ad libero. Quo quae rerum pariatur voluptates aperiam sapiente, sunt quod ducimus corrupti neque voluptas necessitatibus aliquam ex distinctio praesentium vitae sit, ipsum eos, iure perferendis consequuntur. Sint, tempore?
    Accusamus quod cum neque. Labore eos natus nisi consectetur debitis asperiores numquam magni itaque qui, atque, mollitia quaerat cupiditate eius maiores expedita. Iure harum, eveniet perferendis delectus vel voluptates ad.
    Consequuntur fuga nobis in rerum impedit ipsa, optio tempora quis illum quas, odit odio! Debitis omnis, voluptatem incidunt, facere quod sed neque accusamus nostrum reprehenderit totam rerum voluptate impedit soluta!
    Asperiores quod eius error ipsum! Soluta nulla explicabo voluptatum nostrum laudantium doloribus quam molestiae, eligendi perferendis tenetur animi reiciendis recusandae cupiditate ex, ullam porro. Magnam non soluta quas officia ipsum.
    Eius a earum porro modi ratione temporibus dolorum, atque quos, quibusdam optio, expedita sed laborum quia obcaecati. Recusandae, esse sit. Labore fuga ad iste nemo praesentium magnam nulla illo eius.
    Id magni repudiandae vel commodi repellendus neque laudantium debitis, quae, aliquam, voluptate eligendi! Magni expedita, repudiandae, error impedit a, eligendi vero doloremque deleniti dignissimos mollitia dolorem et dolor consectetur corporis?
    Neque eveniet quibusdam ea nihil? Earum, eos minus. Inventore pariatur fugit repellendus officia. Enim necessitatibus, et laborum dolore, iste sint similique voluptates cum animi delectus dignissimos repellat maxime nam totam!
    Perspiciatis autem ea quas nisi laudantium fugiat exercitationem, enim quibusdam recusandae. Blanditiis ea, aut nam odit velit, et voluptatibus sint minus cupiditate voluptas possimus animi necessitatibus deleniti voluptate unde. Modi!
    Unde minus voluptates magni est id, magnam repudiandae quisquam qui vel, dicta delectus voluptate impedit ipsam obcaecati voluptas nobis facere reprehenderit voluptatum quod eos ex recusandae aperiam rem libero. Est?
    Suscipit ab repudiandae voluptas? Corporis earum, esse itaque est provident minus rem, eius saepe voluptatem dolorem impedit fugiat dolores incidunt enim adipisci sed maxime doloribus. Quam accusantium neque iusto labore?
    Blanditiis, explicabo laborum ipsa ea debitis est cupiditate, obcaecati sunt tempore sequi corporis ipsum libero consectetur maxime animi voluptatibus, sint doloribus. Quia, tenetur quibusdam quidem aliquid perferendis facere repellat sit!
    Molestiae cupiditate voluptatibus iure culpa ipsam incidunt quaerat? Expedita sed perspiciatis distinctio alias quas ipsum, cumque amet. Consequuntur minus, quisquam magni nihil fuga libero dolore placeat. Tempora labore magni obcaecati?
    Quis delectus, et distinctio nobis voluptatem veritatis ipsam nesciunt mollitia iste ullam ab repellendus reiciendis numquam itaque corporis iure soluta accusantium culpa fugit at nihil magnam illum tempore sit! Officiis?
    Iste, est harum commodi quam amet itaque repellat unde, inventore vitae ipsa similique, deserunt quasi blanditiis explicabo id voluptatibus corrupti fugiat maxime. Incidunt numquam quasi, earum consequuntur magnam illo amet!
    Rem in quis expedita, fuga molestias dolorem dolores, esse, fugiat non nulla tenetur dignissimos? Possimus pariatur doloremque illum. Maiores, repellendus. Iste voluptate ut sunt laudantium dicta nemo qui quibusdam iusto!
    Impedit officia ipsam dolorem modi? Aliquid voluptate optio repellat inventore, soluta error nam doloribus! Quidem vel inventore in quam voluptates tempore pariatur cumque, soluta autem repellendus iusto doloremque neque quos.
    Similique hic facilis sapiente a non aliquam quaerat aliquid, reprehenderit velit saepe officiis sint iste aperiam maiores ipsum veniam asperiores distinctio eaque voluptates nemo rerum itaque consectetur. Alias, ipsam laborum?
    Laboriosam aspernatur optio praesentium ab natus fuga suscipit accusantium dolorum? Quis quae velit accusantium esse soluta, sint, maiores commodi assumenda possimus facilis odit eligendi maxime quidem, harum eum dolores et?
    Commodi eos repudiandae rem nostrum iusto ipsum amet ducimus recusandae consectetur omnis corporis exercitationem laudantium nemo, est officiis tempora impedit eveniet, cum minus aut libero quisquam alias. Ex, commodi totam.
    Voluptates similique quia quae reiciendis ab assumenda odio provident alias distinctio. Corporis ducimus porro odit sunt mollitia optio recusandae libero praesentium fugit, necessitatibus laboriosam pariatur. Est accusamus dolor nobis consequatur?
    Ducimus ipsam aliquam perspiciatis tenetur eum, suscipit in est unde ex quidem nihil atque fugit quisquam quis laudantium perferendis amet nesciunt possimus, ut modi, explicabo omnis! Cum molestiae vero ut.
    Cumque reprehenderit fugiat dolore officia corporis quisquam quis quam incidunt? Expedita, dolore! Pariatur in beatae dignissimos unde praesentium optio iste suscipit cumque, error dolor soluta inventore eaque voluptas provident nihil!
    Ut sed voluptatibus ad facilis recusandae non id, maiores sunt porro doloribus pariatur? Culpa natus minus repudiandae nihil voluptatibus repellendus totam facilis asperiores dignissimos, impedit fuga, nostrum ducimus dolor cupiditate!</p>
  </div>
</template>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
